on: [push, workflow_dispatch]

jobs:
  check_tag:
    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Find tag (1)
        run: echo "${GITHUB_REF#refs/tags/}"
      - name: Find tag (2)
        run: echo "${{ github.ref }}"
